const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const BEGIN_AUTH = "BEGIN_AUTH"
const COMPLETE_AUTH = "COMPLETE_AUTH"

export {
    SET_CURRENT_USER,
    CLEAR_CURRENT_USER,
    BEGIN_AUTH,
    COMPLETE_AUTH,
}