const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const BEGIN_AUTH = "BEGIN_AUTH"
const COMPLETE_AUTH = "COMPLETE_AUTH"
const ADD_APPOINTMENT = "ADD_APPOINTMENT"
const DELETE_APPOINTMENT= "DELETE_APPOINTMENT"
const GET_APPOINTMENTS = "GET_APPOINTMENTS"
const ADD_REVIEW = "ADD_REVIEW"
const DELETE_REVIEW = "DELETE_REVIEW"
const GET_REVIEWS = "GET_REVIEWS"



export {
    SET_CURRENT_USER,
    CLEAR_CURRENT_USER,
    BEGIN_AUTH,
    COMPLETE_AUTH,
    ADD_APPOINTMENT,
    DELETE_APPOINTMENT,
    GET_APPOINTMENTS,
    ADD_REVIEW,
    DELETE_REVIEW,
    GET_REVIEWS,
}