const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const AUTH_USER = "AUTH_USER"
const COMPLETE_AUTH = "COMPLETE_AUTH"

export {
    SET_CURRENT_USER,
    CLEAR_CURRENT_USER,
    AUTH_USER,
    COMPLETE_AUTH,
}